package com.rubyhuntersky.indexrebellion.presenters.cashediting

import com.rubyhuntersky.indexrebellion.books.SharedRebellionBook
import com.rubyhuntersky.interaction.Interaction
import com.rubyhuntersky.interaction.interactions.cashediting.CashEditingAction
import com.rubyhuntersky.interaction.interactions.cashediting.CashEditingInteraction
import com.rubyhuntersky.interaction.interactions.cashediting.CashEditingVision

object SharedCashEditingInteraction :
    Interaction<CashEditingVision, CashEditingAction> by CashEditingInteraction(SharedRebellionBook)